In [1]:
import pandas as pd

In [2]:
# jan19 = pd.read_csv('Citi/201901-citibike-tripdata.csv')
# feb19 = pd.read_csv('Citi/201902-citibike-tripdata.csv')
# mar19 = pd.read_csv('Citi/201903-citibike-tripdata.csv')
# apr19 = pd.read_csv('Citi/201904-citibike-tripdata.csv')
# may19 = pd.read_csv('Citi/201905-citibike-tripdata.csv')
# jun19 = pd.read_csv('Citi/201906-citibike-tripdata.csv')
# jul19 = pd.read_csv('Citi/201907-citibike-tripdata.csv')
# aug19 = pd.read_csv('Citi/201908-citibike-tripdata.csv')
# sep19 = pd.read_csv('Citi/201909-citibike-tripdata.csv')
# oct19 = pd.read_csv('Citi/201910-citibike-tripdata.csv')
# nov19 = pd.read_csv('Citi/201911-citibike-tripdata.csv')
# dec19 = pd.read_csv('Citi/201912-citibike-tripdata.csv')

jan20 = pd.read_csv('Citi/202001-citibike-tripdata.csv')
feb20 = pd.read_csv('Citi/202002-citibike-tripdata.csv')
mar20 = pd.read_csv('Citi/202003-citibike-tripdata.csv')
apr20 = pd.read_csv('Citi/202004-citibike-tripdata.csv')
may20 = pd.read_csv('Citi/202005-citibike-tripdata.csv')
jun20 = pd.read_csv('Citi/202006-citibike-tripdata.csv')
jul20 = pd.read_csv('Citi/202007-citibike-tripdata.csv')
aug20 = pd.read_csv('Citi/202008-citibike-tripdata.csv')
sep20 = pd.read_csv('Citi/202009-citibike-tripdata.csv')
oct20 = pd.read_csv('Citi/202010-citibike-tripdata.csv')
nov20 = pd.read_csv('Citi/202011-citibike-tripdata.csv')
dec20 = pd.read_csv('Citi/202012-citibike-tripdata.csv')

In [3]:
# jan19.head(4)

In [4]:
jan20.head(4)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,789,2020-01-01 00:00:55.3900,2020-01-01 00:14:05.1470,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,1
1,1541,2020-01-01 00:01:08.1020,2020-01-01 00:26:49.1780,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,1
2,1464,2020-01-01 00:01:42.1400,2020-01-01 00:26:07.0110,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,1
3,592,2020-01-01 00:01:45.5610,2020-01-01 00:11:38.1550,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,1

In [5]:
# covid19 = pd.concat([jan19,feb19,mar19,apr19,may19,jun19,jul19,aug19,sep19,oct19,nov19,dec19], ignore_index= True)
covid20 = pd.concat([jan20,feb20,mar20,apr20,may20,jun20,jul20,aug20,sep20,oct20,nov20,dec20], ignore_index= True)

In [6]:
# covid19.columns

In [7]:
covid20.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [17]:
# covid19[['stardate', 'startime']] = covid19['starttime'].str.split(' ', expand= True)

covid20.tail()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,stardate,startime,enddate,endtime
19506852,2045,2020-12-31 23:58:21.7040,2021-01-01 00:32:27.1570,526,E 33 St & 5 Ave,40.747659,-73.984907,3614,Crescent St & 30 Ave,40.768692,-73.924957,36467,Subscriber,1994,1,2020-12-31,23:58:21.7040,2021-01-01,00:32:27.1570
19506853,288,2020-12-31 23:58:37.8400,2021-01-01 00:03:26.3250,3307,West End Ave & W 94 St,40.794165,-73.974124,3383,Cathedral Pkwy & Broadway,40.804213,-73.966991,47749,Subscriber,1969,0,2020-12-31,23:58:37.8400,2021-01-01,00:03:26.3250
19506854,152,2020-12-31 23:58:52.8090,2021-01-01 00:01:25.6720,3510,Adam Clayton Powell Blvd & W 123 St,40.807832,-73.949373,3518,Lenox Ave & W 126 St,40.808442,-73.945209,48691,Customer,1969,0,2020-12-31,23:58:52.8090,2021-01-01,00:01:25.6720
19506855,654,2020-12-31 23:59:55.9550,2021-01-01 00:10:50.6050,4073,W 51 St & Rockefeller Plaza,40.759700,-73.978082,500,Broadway & W 51 St,40.762288,-73.983362,49564,Subscriber,1994,1,2020-12-31,23:59:55.9550,2021-01-01,00:10:50.6050
19506856,2589,2020-12-31 23:59:57.4070,2021-01-01 00:43:06.4490,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,47364,Customer,1969,0,2020-12-31,23:59:57.4070,2021-01-01,00:43:06.4490

In [9]:
# covid19.head()

In [10]:
covid20[['stardate', 'startime']] = covid20['starttime'].str.split(' ', expand= True)

In [11]:
# covid19[['enddate', 'endtime']] = covid19['stoptime'].str.split(' ', expand= True)

In [12]:
covid20[['enddate', 'endtime']] = covid20['stoptime'].str.split(' ', expand= True)

In [13]:


# covid19['stardate'] = pd.to_datetime(covid19['stardate'])
# covid19['startime'] = pd.to_datetime(covid19['startime'], format='%T').dt.time

In [14]:
covid20.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,stardate,startime,enddate,endtime
0,789,2020-01-01 00:00:55.3900,2020-01-01 00:14:05.1470,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,1,2020-01-01,00:00:55.3900,2020-01-01,00:14:05.1470
1,1541,2020-01-01 00:01:08.1020,2020-01-01 00:26:49.1780,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,1,2020-01-01,00:01:08.1020,2020-01-01,00:26:49.1780
2,1464,2020-01-01 00:01:42.1400,2020-01-01 00:26:07.0110,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,1,2020-01-01,00:01:42.1400,2020-01-01,00:26:07.0110
3,592,2020-01-01 00:01:45.5610,2020-01-01 00:11:38.1550,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,1,2020-01-01,00:01:45.5610,2020-01-01,00:11:38.1550
4,702,2020-01-01 00:01:45.7880,2020-01-01 00:13:28.2400,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,1,2020-01-01,00:01:45.7880,2020-01-01,00:13:28.2400

In [ ]:


# covid20['date'] = pd.to_datetime(covid20['date'])
# covid20['time'] = pd.to_datetime(covid20['time'], format= '%H:%M:%S').dt.time

In [19]:
covid20.tail()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,stardate,startime,enddate,endtime
19506852,2045,2020-12-31 23:58:21.7040,2021-01-01 00:32:27.1570,526,E 33 St & 5 Ave,40.747659,-73.984907,3614,Crescent St & 30 Ave,40.768692,-73.924957,36467,Subscriber,1994,1,2020-12-31,23:58:21.7040,2021-01-01,00:32:27.1570
19506853,288,2020-12-31 23:58:37.8400,2021-01-01 00:03:26.3250,3307,West End Ave & W 94 St,40.794165,-73.974124,3383,Cathedral Pkwy & Broadway,40.804213,-73.966991,47749,Subscriber,1969,0,2020-12-31,23:58:37.8400,2021-01-01,00:03:26.3250
19506854,152,2020-12-31 23:58:52.8090,2021-01-01 00:01:25.6720,3510,Adam Clayton Powell Blvd & W 123 St,40.807832,-73.949373,3518,Lenox Ave & W 126 St,40.808442,-73.945209,48691,Customer,1969,0,2020-12-31,23:58:52.8090,2021-01-01,00:01:25.6720
19506855,654,2020-12-31 23:59:55.9550,2021-01-01 00:10:50.6050,4073,W 51 St & Rockefeller Plaza,40.759700,-73.978082,500,Broadway & W 51 St,40.762288,-73.983362,49564,Subscriber,1994,1,2020-12-31,23:59:55.9550,2021-01-01,00:10:50.6050
19506856,2589,2020-12-31 23:59:57.4070,2021-01-01 00:43:06.4490,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,47364,Customer,1969,0,2020-12-31,23:59:57.4070,2021-01-01,00:43:06.4490

In [15]:
# covidbike = pd.concat([covid20], ignore_index= True)

In [21]:
covid20.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,stardate,startime,enddate,endtime
0,789,2020-01-01 00:00:55.3900,2020-01-01 00:14:05.1470,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,1,2020-01-01,00:00:55.3900,2020-01-01,00:14:05.1470
1,1541,2020-01-01 00:01:08.1020,2020-01-01 00:26:49.1780,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,1,2020-01-01,00:01:08.1020,2020-01-01,00:26:49.1780
2,1464,2020-01-01 00:01:42.1400,2020-01-01 00:26:07.0110,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,1,2020-01-01,00:01:42.1400,2020-01-01,00:26:07.0110
3,592,2020-01-01 00:01:45.5610,2020-01-01 00:11:38.1550,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,1,2020-01-01,00:01:45.5610,2020-01-01,00:11:38.1550
4,702,2020-01-01 00:01:45.7880,2020-01-01 00:13:28.2400,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,1,2020-01-01,00:01:45.7880,2020-01-01,00:13:28.2400

In [23]:
covid20.to_csv('covid20.csv', index= False)